[package]
name = "aux-error"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aux-i18n = { path = "../aux-i18n" }

thiserror = "1.0"
anyhow = "1.0"